### ISSUE TITLE
Добавьте поддержку расширения для Mozilla Firefox 57+

### ISSUE THREAD

**Issue by gegemon2012** [Plastiquewind/youlike-chrome-extension#1]
Собственно, в этом и заключается пожелание/ошибка :-)

**Comment by Plastiquewind** [comment]
Теперь доступно [расширение для Firefox](https://addons.mozilla.org/ru/firefox/addon/youlike-%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%B0%D0%B9%D0%BA%D0%BE%D0%B2/).
