### ISSUE TITLE
Прогресс выполнения проверки.

### ISSUE THREAD

**Issue by gegemon2012** [Plastiquewind/youlike-chrome-extension#2]
Я недавно стал пользоваться расширением на firefox и никак не могу понять делает ли оно что-нибудь или нет. Я нажимаю проверку и ничего не происходит. Может какие-нибудь галочки зеленого цвета справа от списка рядом с проверяемыми идентификаторами или какой нибудь прогресс бар сделать? А то создается впечатление что ничего не происходит...

**Comment by Plastiquewind** [comment]
Загляните в консоль браузера (полагаю, раз Вы тут, то Вам известно, что это), посмотрите, какая там ошибка возникает (она по-любому есть), и скиньте сюда или на почту. Когда проверка действительно выполняется, это явно видно по сообщению "Выполняется проверка".

**Comment by Plastiquewind** [comment]
Закрыл, т.к. 2 недели нет активности.
